// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: devices.sql

package repository

import (
	"context"

	"github.com/google/uuid"
)

const claimDevice = `-- name: ClaimDevice :one
UPDATE devices
SET user_id    = $2,
    status     = 'active',
    claimed_at = now(),
    updated_at = now()
WHERE id = $1 AND status = 'pending'
RETURNING id, user_id, device_identifier, setup_code, display_name, status, mqtt_username, mqtt_password_hash, poll_interval_ms, registered_at, claimed_at, created_at, updated_at
`

type ClaimDeviceParams struct {
	ID     uuid.UUID  `json:"id"`
	UserID *uuid.UUID `json:"user_id"`
}

func (q *Queries) ClaimDevice(ctx context.Context, arg ClaimDeviceParams) (Device, error) {
	row := q.db.QueryRow(ctx, claimDevice, arg.ID, arg.UserID)
	var i Device
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DeviceIdentifier,
		&i.SetupCode,
		&i.DisplayName,
		&i.Status,
		&i.MqttUsername,
		&i.MqttPasswordHash,
		&i.PollIntervalMs,
		&i.RegisteredAt,
		&i.ClaimedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createDevice = `-- name: CreateDevice :one
INSERT INTO devices (device_identifier, setup_code, mqtt_username, mqtt_password_hash)
VALUES ($1, $2, $3, $4)
RETURNING id, user_id, device_identifier, setup_code, display_name, status, mqtt_username, mqtt_password_hash, poll_interval_ms, registered_at, claimed_at, created_at, updated_at
`

type CreateDeviceParams struct {
	DeviceIdentifier string `json:"device_identifier"`
	SetupCode        string `json:"setup_code"`
	MqttUsername     string `json:"mqtt_username"`
	MqttPasswordHash string `json:"mqtt_password_hash"`
}

func (q *Queries) CreateDevice(ctx context.Context, arg CreateDeviceParams) (Device, error) {
	row := q.db.QueryRow(ctx, createDevice,
		arg.DeviceIdentifier,
		arg.SetupCode,
		arg.MqttUsername,
		arg.MqttPasswordHash,
	)
	var i Device
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DeviceIdentifier,
		&i.SetupCode,
		&i.DisplayName,
		&i.Status,
		&i.MqttUsername,
		&i.MqttPasswordHash,
		&i.PollIntervalMs,
		&i.RegisteredAt,
		&i.ClaimedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteDevice = `-- name: DeleteDevice :exec
DELETE FROM devices
WHERE id = $1 AND user_id = $2
`

type DeleteDeviceParams struct {
	ID     uuid.UUID  `json:"id"`
	UserID *uuid.UUID `json:"user_id"`
}

func (q *Queries) DeleteDevice(ctx context.Context, arg DeleteDeviceParams) error {
	_, err := q.db.Exec(ctx, deleteDevice, arg.ID, arg.UserID)
	return err
}

const getDeviceByID = `-- name: GetDeviceByID :one
SELECT id, user_id, device_identifier, setup_code, display_name, status, mqtt_username, mqtt_password_hash, poll_interval_ms, registered_at, claimed_at, created_at, updated_at FROM devices
WHERE id = $1
`

func (q *Queries) GetDeviceByID(ctx context.Context, id uuid.UUID) (Device, error) {
	row := q.db.QueryRow(ctx, getDeviceByID, id)
	var i Device
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DeviceIdentifier,
		&i.SetupCode,
		&i.DisplayName,
		&i.Status,
		&i.MqttUsername,
		&i.MqttPasswordHash,
		&i.PollIntervalMs,
		&i.RegisteredAt,
		&i.ClaimedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDeviceByIdentifier = `-- name: GetDeviceByIdentifier :one
SELECT id, user_id, device_identifier, setup_code, display_name, status, mqtt_username, mqtt_password_hash, poll_interval_ms, registered_at, claimed_at, created_at, updated_at FROM devices
WHERE device_identifier = $1
`

func (q *Queries) GetDeviceByIdentifier(ctx context.Context, deviceIdentifier string) (Device, error) {
	row := q.db.QueryRow(ctx, getDeviceByIdentifier, deviceIdentifier)
	var i Device
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DeviceIdentifier,
		&i.SetupCode,
		&i.DisplayName,
		&i.Status,
		&i.MqttUsername,
		&i.MqttPasswordHash,
		&i.PollIntervalMs,
		&i.RegisteredAt,
		&i.ClaimedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDeviceByMQTTUsername = `-- name: GetDeviceByMQTTUsername :one
SELECT id, user_id, device_identifier, setup_code, display_name, status, mqtt_username, mqtt_password_hash, poll_interval_ms, registered_at, claimed_at, created_at, updated_at FROM devices
WHERE mqtt_username = $1
`

func (q *Queries) GetDeviceByMQTTUsername(ctx context.Context, mqttUsername string) (Device, error) {
	row := q.db.QueryRow(ctx, getDeviceByMQTTUsername, mqttUsername)
	var i Device
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DeviceIdentifier,
		&i.SetupCode,
		&i.DisplayName,
		&i.Status,
		&i.MqttUsername,
		&i.MqttPasswordHash,
		&i.PollIntervalMs,
		&i.RegisteredAt,
		&i.ClaimedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDeviceBySetupCode = `-- name: GetDeviceBySetupCode :one
SELECT id, user_id, device_identifier, setup_code, display_name, status, mqtt_username, mqtt_password_hash, poll_interval_ms, registered_at, claimed_at, created_at, updated_at FROM devices
WHERE setup_code = $1
`

func (q *Queries) GetDeviceBySetupCode(ctx context.Context, setupCode string) (Device, error) {
	row := q.db.QueryRow(ctx, getDeviceBySetupCode, setupCode)
	var i Device
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DeviceIdentifier,
		&i.SetupCode,
		&i.DisplayName,
		&i.Status,
		&i.MqttUsername,
		&i.MqttPasswordHash,
		&i.PollIntervalMs,
		&i.RegisteredAt,
		&i.ClaimedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listDevicesByUserID = `-- name: ListDevicesByUserID :many
SELECT id, user_id, device_identifier, setup_code, display_name, status, mqtt_username, mqtt_password_hash, poll_interval_ms, registered_at, claimed_at, created_at, updated_at FROM devices
WHERE user_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListDevicesByUserID(ctx context.Context, userID *uuid.UUID) ([]Device, error) {
	rows, err := q.db.Query(ctx, listDevicesByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Device{}
	for rows.Next() {
		var i Device
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.DeviceIdentifier,
			&i.SetupCode,
			&i.DisplayName,
			&i.Status,
			&i.MqttUsername,
			&i.MqttPasswordHash,
			&i.PollIntervalMs,
			&i.RegisteredAt,
			&i.ClaimedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDevice = `-- name: UpdateDevice :one
UPDATE devices
SET display_name     = $2,
    poll_interval_ms = $3,
    updated_at       = now()
WHERE id = $1 AND user_id = $4
RETURNING id, user_id, device_identifier, setup_code, display_name, status, mqtt_username, mqtt_password_hash, poll_interval_ms, registered_at, claimed_at, created_at, updated_at
`

type UpdateDeviceParams struct {
	ID             uuid.UUID  `json:"id"`
	DisplayName    string     `json:"display_name"`
	PollIntervalMs int64      `json:"poll_interval_ms"`
	UserID         *uuid.UUID `json:"user_id"`
}

func (q *Queries) UpdateDevice(ctx context.Context, arg UpdateDeviceParams) (Device, error) {
	row := q.db.QueryRow(ctx, updateDevice,
		arg.ID,
		arg.DisplayName,
		arg.PollIntervalMs,
		arg.UserID,
	)
	var i Device
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DeviceIdentifier,
		&i.SetupCode,
		&i.DisplayName,
		&i.Status,
		&i.MqttUsername,
		&i.MqttPasswordHash,
		&i.PollIntervalMs,
		&i.RegisteredAt,
		&i.ClaimedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateDeviceMQTTCredentials = `-- name: UpdateDeviceMQTTCredentials :one
UPDATE devices
SET mqtt_username      = $2,
    mqtt_password_hash = $3,
    updated_at         = now()
WHERE id = $1
RETURNING id, user_id, device_identifier, setup_code, display_name, status, mqtt_username, mqtt_password_hash, poll_interval_ms, registered_at, claimed_at, created_at, updated_at
`

type UpdateDeviceMQTTCredentialsParams struct {
	ID               uuid.UUID `json:"id"`
	MqttUsername     string    `json:"mqtt_username"`
	MqttPasswordHash string    `json:"mqtt_password_hash"`
}

func (q *Queries) UpdateDeviceMQTTCredentials(ctx context.Context, arg UpdateDeviceMQTTCredentialsParams) (Device, error) {
	row := q.db.QueryRow(ctx, updateDeviceMQTTCredentials, arg.ID, arg.MqttUsername, arg.MqttPasswordHash)
	var i Device
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DeviceIdentifier,
		&i.SetupCode,
		&i.DisplayName,
		&i.Status,
		&i.MqttUsername,
		&i.MqttPasswordHash,
		&i.PollIntervalMs,
		&i.RegisteredAt,
		&i.ClaimedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateDeviceStatus = `-- name: UpdateDeviceStatus :one
UPDATE devices
SET status     = $2,
    updated_at = now()
WHERE id = $1
RETURNING id, user_id, device_identifier, setup_code, display_name, status, mqtt_username, mqtt_password_hash, poll_interval_ms, registered_at, claimed_at, created_at, updated_at
`

type UpdateDeviceStatusParams struct {
	ID     uuid.UUID    `json:"id"`
	Status DeviceStatus `json:"status"`
}

func (q *Queries) UpdateDeviceStatus(ctx context.Context, arg UpdateDeviceStatusParams) (Device, error) {
	row := q.db.QueryRow(ctx, updateDeviceStatus, arg.ID, arg.Status)
	var i Device
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DeviceIdentifier,
		&i.SetupCode,
		&i.DisplayName,
		&i.Status,
		&i.MqttUsername,
		&i.MqttPasswordHash,
		&i.PollIntervalMs,
		&i.RegisteredAt,
		&i.ClaimedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
