// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repository

import (
	"database/sql/driver"
	"fmt"
	"time"

	"github.com/google/uuid"
)

type DeviceStatus string

const (
	DeviceStatusPending  DeviceStatus = "pending"
	DeviceStatusActive   DeviceStatus = "active"
	DeviceStatusDisabled DeviceStatus = "disabled"
)

func (e *DeviceStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = DeviceStatus(s)
	case string:
		*e = DeviceStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for DeviceStatus: %T", src)
	}
	return nil
}

type NullDeviceStatus struct {
	DeviceStatus DeviceStatus `json:"device_status"`
	Valid        bool         `json:"valid"` // Valid is true if DeviceStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullDeviceStatus) Scan(value interface{}) error {
	if value == nil {
		ns.DeviceStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.DeviceStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullDeviceStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.DeviceStatus), nil
}

func (e DeviceStatus) Valid() bool {
	switch e {
	case DeviceStatusPending,
		DeviceStatusActive,
		DeviceStatusDisabled:
		return true
	}
	return false
}

func AllDeviceStatusValues() []DeviceStatus {
	return []DeviceStatus{
		DeviceStatusPending,
		DeviceStatusActive,
		DeviceStatusDisabled,
	}
}

type Device struct {
	ID               uuid.UUID    `json:"id"`
	UserID           *uuid.UUID   `json:"user_id"`
	DeviceIdentifier string       `json:"device_identifier"`
	SetupCode        string       `json:"setup_code"`
	DisplayName      string       `json:"display_name"`
	Status           DeviceStatus `json:"status"`
	MqttUsername     string       `json:"mqtt_username"`
	MqttPasswordHash string       `json:"mqtt_password_hash"`
	PollIntervalMs   int64        `json:"poll_interval_ms"`
	RegisteredAt     time.Time    `json:"registered_at"`
	ClaimedAt        *time.Time   `json:"claimed_at"`
	CreatedAt        time.Time    `json:"created_at"`
	UpdatedAt        time.Time    `json:"updated_at"`
}

type RefreshToken struct {
	ID        uuid.UUID `json:"id"`
	UserID    uuid.UUID `json:"user_id"`
	TokenHash string    `json:"token_hash"`
	ExpiresAt time.Time `json:"expires_at"`
	CreatedAt time.Time `json:"created_at"`
}

type SensorReading struct {
	Time         time.Time `json:"time"`
	DeviceID     uuid.UUID `json:"device_id"`
	TemperatureC *float64  `json:"temperature_c"`
	HumidityPct  *float64  `json:"humidity_pct"`
	Eco2Ppm      *float64  `json:"eco2_ppm"`
	TvocPpb      *float64  `json:"tvoc_ppb"`
	Pm25Ugm3     *float64  `json:"pm25_ugm3"`
	Pm10Ugm3     *float64  `json:"pm10_ugm3"`
}

type User struct {
	ID           uuid.UUID `json:"id"`
	Email        string    `json:"email"`
	PasswordHash string    `json:"password_hash"`
	DisplayName  string    `json:"display_name"`
	CreatedAt    time.Time `json:"created_at"`
	UpdatedAt    time.Time `json:"updated_at"`
}
