// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sensor_readings.sql

package repository

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const getLatestSensorReading = `-- name: GetLatestSensorReading :one
SELECT time, device_id, temperature_c, humidity_pct, eco2_ppm, tvoc_ppb, pm25_ugm3, pm10_ugm3 FROM sensor_readings
WHERE device_id = $1
ORDER BY time DESC
LIMIT 1
`

func (q *Queries) GetLatestSensorReading(ctx context.Context, deviceID uuid.UUID) (SensorReading, error) {
	row := q.db.QueryRow(ctx, getLatestSensorReading, deviceID)
	var i SensorReading
	err := row.Scan(
		&i.Time,
		&i.DeviceID,
		&i.TemperatureC,
		&i.HumidityPct,
		&i.Eco2Ppm,
		&i.TvocPpb,
		&i.Pm25Ugm3,
		&i.Pm10Ugm3,
	)
	return i, err
}

const getRawSensorReadings = `-- name: GetRawSensorReadings :many
SELECT time, device_id, temperature_c, humidity_pct, eco2_ppm, tvoc_ppb, pm25_ugm3, pm10_ugm3 FROM sensor_readings
WHERE device_id = $1
  AND time >= $2
  AND time <= $3
ORDER BY time ASC
`

type GetRawSensorReadingsParams struct {
	DeviceID uuid.UUID `json:"device_id"`
	Time     time.Time `json:"time"`
	Time_2   time.Time `json:"time_2"`
}

func (q *Queries) GetRawSensorReadings(ctx context.Context, arg GetRawSensorReadingsParams) ([]SensorReading, error) {
	rows, err := q.db.Query(ctx, getRawSensorReadings, arg.DeviceID, arg.Time, arg.Time_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SensorReading{}
	for rows.Next() {
		var i SensorReading
		if err := rows.Scan(
			&i.Time,
			&i.DeviceID,
			&i.TemperatureC,
			&i.HumidityPct,
			&i.Eco2Ppm,
			&i.TvocPpb,
			&i.Pm25Ugm3,
			&i.Pm10Ugm3,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertSensorReading = `-- name: InsertSensorReading :exec
INSERT INTO sensor_readings (time, device_id, temperature_c, humidity_pct, eco2_ppm, tvoc_ppb, pm25_ugm3, pm10_ugm3)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
`

type InsertSensorReadingParams struct {
	Time         time.Time `json:"time"`
	DeviceID     uuid.UUID `json:"device_id"`
	TemperatureC *float64  `json:"temperature_c"`
	HumidityPct  *float64  `json:"humidity_pct"`
	Eco2Ppm      *float64  `json:"eco2_ppm"`
	TvocPpb      *float64  `json:"tvoc_ppb"`
	Pm25Ugm3     *float64  `json:"pm25_ugm3"`
	Pm10Ugm3     *float64  `json:"pm10_ugm3"`
}

func (q *Queries) InsertSensorReading(ctx context.Context, arg InsertSensorReadingParams) error {
	_, err := q.db.Exec(ctx, insertSensorReading,
		arg.Time,
		arg.DeviceID,
		arg.TemperatureC,
		arg.HumidityPct,
		arg.Eco2Ppm,
		arg.TvocPpb,
		arg.Pm25Ugm3,
		arg.Pm10Ugm3,
	)
	return err
}
